# Generated by Django 4.2.1 on 2023-06-07 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("media", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PostContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("text_content", models.TextField(default="")),
                ("pub_date", models.DateTimeField(auto_now=True)),
                ("pub_location", models.CharField(max_length=100, null=True)),
                (
                    "favourite_users",
                    models.ManyToManyField(
                        related_name="favourited_posts", to="users.myuser"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="postcontents", to="media.image"
                    ),
                ),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="liked_posts", to="users.myuser"
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.myuser"
                    ),
                ),
                ("tags", models.ManyToManyField(to="posts.tag")),
                (
                    "videos",
                    models.ManyToManyField(
                        related_name="postcontents", to="media.video"
                    ),
                ),
            ],
        ),
    ]
