# Generated by Django 4.2.1 on 2023-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontent",
            name="comments",
            field=models.ManyToManyField(
                related_name="post_comments", to="posts.comments"
            ),
        ),
    ]
