# Generated by Django 4.2.1 on 2023-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_postcontent_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontent",
            name="text_type",
            field=models.CharField(default="string", max_length=100),
        ),
    ]
