# Generated by Django 4.2.1 on 2023-06-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("media", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="myuser_groups", to="auth.group"
                    ),
                ),
                (
                    "profile_picture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.image",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="myuser_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "MyUser",
                "verbose_name_plural": "MyUsers",
            },
        ),
    ]
