# Generated by Django 4.2.1 on 2023-06-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="blacklist",
            field=models.ManyToManyField(
                related_name="user_blacklists", to="users.myuser"
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="follow",
            field=models.ManyToManyField(
                related_name="user_follows", to="users.myuser"
            ),
        ),
    ]
