# Generated by Django 4.2.1 on 2023-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_myuser_blacklist_myuser_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
