# Generated by Django 4.2.1 on 2023-06-09 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_messagethread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
