# Generated by Django 4.2.1 on 2023-06-09 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_devicetoken_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
