# Generated by Django 4.2.1 on 2023-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_alter_devicetoken_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
