# Generated by Django 4.2.1 on 2023-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_alter_devicetoken_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
