# Generated by Django 4.2.1 on 2023-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_devicetoken_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
